### ISSUE TITLE
TS2304: Cannot find name 'XMLHttpRequestResponseType'.

### ISSUE THREAD

**Issue by JanEggers** [aspnet/SignalR#1375]
i updated my playground to 

"@aspnet/signalr": "^1.0.0-preview1-28189"

and now i cant compile anymore.

    [at-loader] ./node_modules/@aspnet/signalr/dist/esm/HttpClient.d.ts:7:20 
TS2304: Cannot find name 'XMLHttpRequestResponseType'.

can you give me a hint what im missing?

here is the code:

https://github.com/JanEggers/Playground/tree/signalr

**Comment by anurse** [comment]
It looks like the typescript compiler you are using is out of date. I updated the version of typescript in your package.json and didn't get that error anymore. Unfortunately, I then started getting this error: https://github.com/ReactiveX/rxjs/issues/2705, but it looks like there are some resolutions in that thread for that issue.

**Comment by anurse** [comment]
For reference, I used `npm up typescript` to update to `"typescript": "^2.7.1"`

**Comment by JanEggers** [comment]
thx i had to updat all the stuff but now its working again. is it possible to add min required typescript version as peerdependency so one gets at least a warning agout it?

**Comment by anurse** [comment]
We wouldn't want to do that, because it would print a lot of warnings about it when anyone installs it, even if they aren't using TypeScript. The issue is with the `.d.ts` files, the SignalR client itself is shipped as `.js` files, so we wouldn't want to bring typescript (or warnings about typescript) in for people who aren't using it.

**Comment by JanEggers** [comment]
then please mention it in the readme

**Comment by granthoff1107** [comment]
@anurse, I want to use this in Ionic Framework, the lastest support version of typescript is ~2.4.2.  How can I Import the signalR using the raw Javascript?

**Comment by anurse** [comment]
> the lastest support version of typescript is ~2.4.2

What do you mean by this? Ionic shouldn't force you to use an older version of TypeScript, it's a JavaScript framework. The most recent version of TypeScript should work fine with it as far as I know.

Are you seeing an error using the latest TypeScript with Ionic?

**Comment by granthoff1107** [comment]
Yeah, last time I tried to upgrade ionic it broke compilation.  Ionic 4 is built on typescript 2.8.3 but I fixed this by just using a manual require like so 

    npm i @types/node
  
    declare var require: any

    const { HubConnection, HubConnectionBuilder } =  require('@aspnet/signalr');

**Comment by Jelledb** [comment]
> nodejs-player@0.0.1 start:backend C:\Users\*******\Documents\*********\nodejs
> cd backend && tsc -v && tsc && node ./bin/start.js

Version 2.9.2
../node_modules/@aspnet/signalr/dist/esm/HttpClient.d.ts(16,20): error TS2304: Cannot find name 'XMLHttpRequestResponseType'.

I'm still getting this with the newest version of typescript?

**Comment by anurse** [comment]
Are you using SignalR from a NodeJS application or a Browser application? If you're using NodeJS, you need to add a polyfill for `XMLHttpRequest`. We don't have full official support for NodeJS in the SignalR client right now (the priority for v1 was Browsers) but are working to improve it in the next release (see #2535)
