### ISSUE TITLE
DateTime.Kind no longer honored in SignalR RPC

### ISSUE THREAD

**Issue by sonicmouse** [aspnet/SignalR#2305]
I upgraded to `v1.0.0-rc1-final` and I am seeing new behavior.

From the server, I call a method on the client. The parameter object is of type `DateTime`. The `DateTime` object has the `Kind` property set to `Utc`. When it gets to the client method, the `DateTime` object has a `Kind` property of `Local`.

In previous versions of SignalR it would keep the `Kind` as `Utc` across RPCs.

Is this expected now? Do i really have to do a UTC conversion in all SignalR RPCs even if it was originally sent at UTC?

I believe this is an issue that should be changed back to how it previously worked.

**Comment by davidfowl** [comment]
> I upgraded to v1.0.0-rc1-final and I am seeing new behavior.

I'm trying to unpack this statement. Maybe the next step is to send us a repro project showing exactly how you configured the application.

**Comment by sonicmouse** [comment]
Take a test SignalR server/client. Add this to the client:

```
            _hub.On("testDateTimeUTC", new Type[] { typeof(DateTime) }, (o) =>
            {
                System.Diagnostics.Debug.Assert(((DateTime)o[0]).Kind == DateTimeKind.Utc);
                return Task.CompletedTask;
            });
```

Then in the server, call this:
`await proxy.SendAsync("testDateTimeUTC", DateTime.UtcNow);`

The assertion will be hit.

**Comment by sonicmouse** [comment]
```
            _hub = new HubConnectionBuilder()
                .WithUrl(_envSettings.CreatePlayerServiceHubPath(), (x) =>
                {
                    x.Headers.Add("RegistrationKey", regCode);
                    x.Headers.Add("DeviceName", deviceName);
                    x.Headers.Add("TimeZoneOffset", Services.TimeService.TimeZoneOffset.ToString());
                })
                .Build();
```
There are some properties I am adding in that are pertinent to the client connection as header objects. Just string objects. For example `regCode` is a typical registration code "12345-12345-12345", `deviceName` is a simple name like "ABCDEFG-12345", and timezone offset looks like "-5:00"

**Comment by davidfowl** [comment]
@JamesNK any ideas?

**Comment by JamesNK** [comment]
Hmmm, I think parameters are still going through the serializer. I'm not sure what else could have changed to cause this off the top of my head.

**Comment by sonicmouse** [comment]
Are you guys seeing this? Did you try it? Or is it just me?

**Comment by davidfowl** [comment]
I can reproduce it.

**Comment by davidfowl** [comment]
@JamesNK has a bad memory 😉. We made this change intentionally to solve this problem https://github.com/aspnet/SignalR/issues/1346. Seems like you can't even work around it by setting the right appropriate json options. We're going to make it so you can at least set the option to control the handling here. 

@JamesNK is there any reason you didn't set the default option instead of changing it on the reader? https://github.com/aspnet/SignalR/blob/bff2060454fc15d8633839714c14388757908833/src/Microsoft.AspNetCore.SignalR.Protocols.Json/Protocol/JsonHubProtocol.cs#L135

**Comment by JamesNK** [comment]
Fixed. You could use DateTimeOffset instead until the next release. When the time zone is zero then it is UTC.

**Comment by anurse** [comment]
Re-closing, we're going to open new issues for patch work.

**Comment by sonicmouse** [comment]
Not to beat a dead horse here, but I am assuming this fix didn't make it in to v1.0.0?
I just updated via nuget and this issue still persists and want to know if it's me that's screwing something up.

thanks

**Comment by BrennanConroy** [comment]
No, this will be in the patch 1.0.1

**Comment by sonicmouse** [comment]
Thanks, Brennan
