### ISSUE TITLE
HubConnection.start fails after previous stop

### ISSUE THREAD

**Issue by ArtemAvramenko** [aspnet/SignalR#2783]
let connection = new signalR.HubConnectionBuilder()
        .withUrl('http://localhost:65432/myHub')
        .build();

    connection.start()
        .then(() => console.log('Connected'))
        .then(() => connection.stop())
        .then(() => console.log('Disconnected'))
        .then(() => connection.start()) // <--- fails here
        .then(() => console.log('Reconnected'))
        .catch(e => console.error(e.message));

The reconnect fails in any browser. The log shows this:
> Cannot send data if the connection is not in the 'Connected' State.

* Versions of Server-Side NuGet Packages: 2.3.0
* Versions of Client-Side NPM Packages: 1.0.2
* Are you using the C# client or the JavaScript client: Javascript
* The Server you are using: IIS/IIS Express (AspNetCoreModule)
* The Operating System on the Server: Windows 10
* The Operating System on the Client: Windows 10
* The Browser on the client, if using the JavaScript client: any (IE/Chrome/Edge/Firefox):

**Comment by ArtemAvramenko** [comment]
Server log:

    Hosting environment: Development
    Content root path: C:\....
    Now listening on: http://localhost:2530
    Application started. Press Ctrl+C to shut down.


Client log:

    Debug: Starting HubConnection.
    Debug: Starting connection with transfer format 'Text'.
    Debug: Sending negotiation request: http://localhost:65432/myHub/negotiate
    Debug: Selecting transport 'WebSockets'
    Trace: (WebSockets transport) Connecting
    Information: WebSocket connected to ws://localhost:65432/myHub?id=...
    Debug: Sending handshake request.
    Trace: (WebSockets transport) sending data. String data of length 32.
    Information: Using HubProtocol 'json'.
    Connected
    Debug: Stopping HubConnection.
    Disconnected
    Debug: Starting HubConnection.
    Debug: Starting connection with transfer format 'Text'.
    Debug: Sending negotiation request: http://localhost:65432/appHub/negotiate
    Trace: (WebSockets transport) socket closed.
    Information: Connection disconnected.
    Debug: Sending handshake request.
    Error: Cannot send data if the connection is not in the 'Connected' State.

**Comment by BrennanConroy** [comment]
@ArtemAvramenko Could you collect server logs with a more verbose log level? https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#server-side-logging

Also, could you collect logs that match for the client and server? Currently your logs say the server is on `2530` and your client is connecting to `65432`

And your client logs look like they may have been stitched together because half of it is connecting to `myHub` and the other half is connecting to `appHub`. So it would be good to have logs that are copy pasted without being edited (unless you are removing auth tokens which is fine).

**Comment by ArtemAvramenko** [comment]
As I understand, the following code works in your environment:

    connection.start()
        .then(() => connection.stop())
        .then(() => connection.start())

Right?

In my environment, bug is 100% reproducible.

>Currently your logs say the server is on 2530 and your client is connecting to 65432

As designed, because it is Kesterel over IIS Express.

**Comment by BrennanConroy** [comment]
I can hit this now, and it only repros when using the WebSockets transport. SSE and LongPolling work fine. Will investigate.

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/aspnet/SignalR/commit/53ceaf1b2c29aaa22a0c039609e2b34e27120396

**Comment by ArtemAvramenko** [comment]
Unfortunately, still reproduced:
> Cannot send data if the connection is not in the 'Connected' State.

But sometimes I get another error:
> Cannot set property 'onreceive' of null

* Versions of Server-Side NuGet Packages: 1.0.3
* Versions of Client-Side NPM Packages: 1.1.0-preview1-35029
* Are you using the C# client or the JavaScript client: Javascript
* The Server you are using: IIS/IIS Express (AspNetCoreModule)
* The Operating System on the Server: Windows 10
* The Operating System on the Client: Windows 10
* The Browser on the client, if using the JavaScript client: any (IE/Chrome/Edge/Firefox)

**Comment by BrennanConroy** [comment]
Is this with the same code you provided?
```
let connection = new signalR.HubConnectionBuilder()
    .withUrl('http://localhost:65432/myHub')
    .build();

connection.start()
    .then(() => console.log('Connected'))
    .then(() => connection.stop())
    .then(() => console.log('Disconnected'))
    .then(() => connection.start()) // <--- fails here
    .then(() => console.log('Reconnected'))
    .catch(e => console.error(e.message));
```

**Comment by ArtemAvramenko** [comment]
Yes, code is same.

Now I use a workaround: build new connection after each disconnect.

**Comment by BrennanConroy** [comment]
I can't hit this issue, and I did a few hundred restarts with the same connection. Is it possible the client was cached in the browser and is still running the old version?

**Comment by ArtemAvramenko** [comment]
I can check this only next week, but I am almost sure that client was new. This follows from the fact that I start to get another error:
> Cannot set property 'onreceive' of null

Also with new build I get error with long polling, not only with WebSockets.
