### ISSUE TITLE
HubConnection.StartAsync never returning when called from IIS hosted ASP.NET project

### ISSUE THREAD

**Issue by Kampfmoehre** [aspnet/SignalR#728]
### HubConnection.StartAsync never returning when called from IIS hosted ASP.NET project
When I try to start a connection from a client that is hosted in IIS 7.5 in a .NET 4.6.1 project to a ASP.NET Core Kestrel server, it never returns after the options request.
When I open the connection from a client in a console project, it works as expected.

### Minimal repro steps
1. Set up a server project with ASP.NET Core 2 and use SignalR in startup
```csharp
public class Startup
{
    public IServiceProvider ConfigureServices(IServiceCollection services)
    {
        services.AddSignalR();
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        app.UseSignalR(routes =>
        {
            routes.MapHub<SampleHub>("sample");
        });
    }
}

public class SampleHub : Hub
{
    ILogger _logger;
    public SampleHub(ILogger<SampleHub> logger)
    {
        _logger = logger;
    }

    public async Task<Output> SampleMethod(Input input)
    {
        return await SomeHelper.Sample(input, _logger);
    }
}
```

Relevant references in the server project:
```xml
<PackageReference Include="Microsoft.AspNetCore" Version="2.1.0-preview1-26636"/>
<PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.1.0-preview1-26636"/>
<PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.1.0-preview1-26636"/>
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.0-preview1-26636"/>
<PackageReference Include="Microsoft.AspNetCore.Rewrite" Version="2.1.0-preview1-26636"/>
<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha1-26636"/>
<PackageReference Include="Microsoft.AspNetCore.SignalR.Http" Version="1.0.0-alpha1-26636"/>
<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.0-preview1-26636"/>
<PackageReference Include="Microsoft.AspNetCore.WebSockets" Version="2.1.0-preview1-26636"/>
```
2. Add a second project with a client template
3. Add the following references to the client project
```xml
<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="1.0.0-alpha1-26636"/>
<PackageReference Include="Microsoft.AspNetCore.Sockets.Client.Http" Version="1.0.0-alpha1-26636"/>
<PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0"/>
```
4. Add a Client class to the project
```csharp
public abstract class Client : IDisposable
{
    private readonly ILoggerFactory _loggerFactory;
    private HubConnection _connection;

    public Client(ILoggerFactory loggerFactory)
    {
        _loggerFactory = loggerFactory;
    }
    public async Task ConnectAsync(Uri baseUrl, bool useLocalLazyLoad)
    {
        Task<HubConnection> connectionTask = ConnectToHubEndpointAsync(new Uri(baseUrl, "sample"), null);
        
        await Task.WhenAll(connectionTask);

        _connection = connectionTask.Result;
    }

    public async Task<Output> SampleAsync(Input input)
    {
        return await _connection.InvokeAsync<Output>("sample", input);
    }

    private async Task<HubConnection> ConnectToHubEndpointAsync(Uri uri, Action<HubConnection> configureConnection)
    {
        TransportType transportType = GetTransportTypeFromOS();
        Console.WriteLine($"Running on {RuntimeInformation.OSDescription} connection to {uri} using transport type {transportType}");

        var result = new HubConnection(new HttpConnection(uri, transportType, _loggerFactory));
        configureConnection?.Invoke(result);

        await result.StartAsync();

        return result;
    }

    private TransportType GetTransportTypeFromOS()
    {
        if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            return TransportType.WebSockets;

        const int versionOffset = 18;
        var versionStr = RuntimeInformation.OSDescription.Substring(versionOffset);
        if (!Version.TryParse(versionStr, out Version version))
            return TransportType.LongPolling;

        if (version.Major > 6 || (version.Major == 6 && version.Minor >= 2))
            return TransportType.WebSockets;

        return TransportType.LongPolling;
    }

    // ... Dispose and other stuff
}
```
5. Create a NuGet package of the client project
6. Set up a project with .NET Framework 4.6.1 containing an ASP.NET Web Application
7. Add the NuGet package you created in step 5 (with it comes NETStandard.Library, Microsoft.NETCore.Platforms, ASP.NETCore and SignalR as well as a bunch of System.* packages)
8. Add a controller to the project
```csharp
public class HomeController : Controller
{
    static Uri _uri = new Uri("http://localhost:5000");

    public ActionResult Index()
    {
        ViewBag.Title = "Home Page";

        foo().Wait();

        return View();
    }

    static async Task foo()
    {
        using (var client = new TestClient(null))
        {
            await client.ConnectAsync(_uri, false);

            var input = new Input
            {
                Id = Guid.NewGuid()
            };
            input.ClientId = client.ClientId;

            var output = await client.SampleAsync(input);
        }
    }
}

public class TestClient : Client
{
    public TestClient(ILoggerFactory loggerFactory)
        : base(loggerFactory)
    {
    }
}
```
9. Host the project in IIS and call the route to the home controller

### Expected result
The client connects and calls the sample method.

### Actual result
The client doesn't seem to recieve the answer from the server while connecting.

### Further technical details
I have an ASP.NET Core 2(.1) server project with with SignalR. This project offers an abstract client template to connect to the server which is .NETStandard2.0.
I have another project in .NET Framework 4.6.1 that implements the client (recieving the client project over a NuGet package). The client starts a connection to the hub on the server the following way:

```csharp
var result = new HubConnection(new HttpConnection(uri, transportType, _loggerFactory));
await result.StartAsync();
```

The .NET Framework solutions contains another (test) project which is a console project. When I use the client in this project, everything works fine, the client connects and I can use the connection. However, the solution contains another project, which is an ASP.NET Web Application. This is hosted on my IIS locally and when I try to connect the client it never finishes.

I have cloned this repository and debugged into SignalR and I can see it runs fine until [this line in HttpConnection.cs](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs#L201) where it would send the options request to get the connection ID but it is never returning. I can see in the server log that the request is processed, but the client seems to never recieve the answer.

This is the log output when I connect from the client in the console application:
```
[08:21:05 INF] Request starting HTTP/1.1 OPTIONS http://localhost:5000/sample  0
[08:21:05 INF] Request finished in 198.5549ms 200 application/json
[08:21:06 INF] Request starting HTTP/1.1 GET http://localhost:5000/sample?id=63aadd5b-5de3-4f31-8f74-ae48179a3b2d
...
```

And this is the log output when I connect from the client running from IIS:
```
[08:42:16 INF] Request starting HTTP/1.1 OPTIONS http://localhost:5000/sample  0
[08:42:16 INF] Request finished in 1.7731ms 200 application/json

```
The request won't ever finish.

### Additional Notes
I updated .NET Core to final 2.0 yesterday and all ASP.NET Core references to 2.1.0-preview1-26636 and SignalR to 1.0.0-alpha1-26636, but I had the problem before with ASP.NET Core 2.0.0-preview2-final and SignalR 1.0.0-preview2-25794 under .NET Core 2.0.0 preview 2.

Can someone give me a hint what could cause this problem? Maybe IIS is blocking the request somehow?

The client does open another connection over which additional data is transferred, which is the reason it exists as a template. For simplicity I omitted these parts in the samples as well as the models used. These are in an additional assembly which is as well references as a NuGet package in the API project.

The debugging is based on a test project I set up, to exclude that the problem is coming from our real project, which is a big API that is hosted either in IIS or selfhosted with a windows service. The self hosted one works as expected so it seems to be a problem with IIS. This is the reason I also tested the connection in a console project which works fine. Unfortunately contains the server and the test project enough internal code that I can't upload it to github. I am hoping someone can point me out where I should look for the problem or what I can do to further investigate it.

**Comment by davidfowl** [comment]
Does it work fine when using kestrel directly?

**Comment by Kampfmoehre** [comment]
For clarification, it is unrelevant if the server part is run in any terminal with dotnet run or is hosted in IIS or is started with VSCode Debugger. All works fine, when the client is run from console.  The only problem is, when the client is hosted in IIS.

We have UseIISIntegration in program.cs:
```csharp
var host = new WebHostBuilder()
     .UseConfiguration(config)
    .UseKestrel()
    .UseContentRoot(Directory.GetCurrentDirectory())
    .UseIISIntegration()
    .UseStartup<Startup>()
    .Build();

host.Run();
```

Or is there any other thing you mean with "using kestrel directly"?

**Comment by davidfowl** [comment]
> The only problem is, when the client is hosted in IIS.

I see, the problem is when using the *client* API on the server side. 

> Set up a project with .NET Framework 4.6.1 containing an ASP.NET Web Application

On top of that you're using an ASP.NET MVC 5 application as the client. So you're using System.Web.

I just want to confirm all of the moving pieces here. 

Wild guess is that it's this issue https://github.com/aspnet/SignalR/issues/545.

To verify, put your Start in a `Task.Run` and see if that works.

**Comment by Kampfmoehre** [comment]
To specify it further, by client I mean a client in terms of connection client to our server. This client is used in a API project which is either hosted in IIS or run selfhosted in a Windows service. I set up a simple test project to imitate the web API and exclude other parts in that big API as cause. This test project is a simple ASP.NET MVC 5 project which is hosted in IIS. When this project creates a client and tries to connect it to the server, the problem also occurs, as in the original WEB API project.

The original client, which opens the HubConnection and calls StartAsync() may be written in the NETStandard2.0 project, but it is used and run in the .NET Framework 4.6.1 project. While it runs, when startet in another .NET 4.6.1 console project, it fails when fired from the IIS.

So client (side) is either an .NET Framework 4.6.1 Console Application or an IIS hosted ASP.NET MVC 5 application, server (side) is just the posted .NETCoreApp2.0 project with ASP.NET Core and SignalR using Kestrel with dotnet run on command line or hosted in an IIS.

As said, I have debugged it to the point where it sends the options request to the server, where the client code never returns. In Wireshark I can see the options request is responded correctly on server side, Also when I send this request with Postman it is responded correct as well.

Please let me know if anything is unclear, maybe I am not perfect at explaining. Thank you for your help so far.

> To verify, put your Start in a Task.Run and see if that works.

Which start do you mean, the call to ConnectAsync which is awaited in the HomeController?

**Comment by davidfowl** [comment]
> Which start do you mean, the call to ConnectAsync which is awaited in the HomeController?

I edited the comment. Yes.

**Comment by Kampfmoehre** [comment]
Ok thank you very much, putting the call to ConnectAsync in a Task.Run solves the problem (kind of). Actual code now looks like this:
```csharp
static async Task foo()
{
    using (var client = new TestClient(null))
    {
        var test = await Task.Run(async () =>
        {
            await client.ConnectAsync(_uri, false);

            var input = new Input
            {
                Id = Guid.NewGuid()
            };

            var output = await client.SampleAsync(input);
        });
    }
}
```

So why this solves the problem at least in my test project, I do not understand why it works this way. I will try and see if this also works in the actual API project.

**Comment by mikaelm12** [comment]
This has been fixed in a200cd46b19d101e2c445a356af9ff4318bdf432

**Comment by lslewis901** [comment]
The "500 error" issue with IIS and using a ASPNET CORE client to access the HUB - still exists for me, using Microsoft.AspNetCore.SignalR.Client (1.0.0-alpha1-final).

Error message is: HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).

If I use just ASPNET Core Kestrel by itself everything is fine.

**Comment by BrennanConroy** [comment]
Have you enabled WebSockets in IIS?

**Comment by lslewis901** [comment]
Good question, as it turns out this is on my local PC which is running Windows 7/IIS 7.5

Windows 7 is considered a Down-Level Operating system and doesn't support Web Sockets. A Known Issue and Limitation.

**Comment by BrennanConroy** [comment]
Yeah, you should check the 2016 machine for websockets. And on Win7 you'll need to use a different transport.
