### ISSUE TITLE
No-cache does not seem to work for IE

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#848]
As per: https://github.com/aspnet/SignalR/commit/325c909dffcd3cd5e7b174869a29c78d00474564#commitcomment-24230784

> I'm using the latest version. I added all ts files in my project and compiled it to es5. I also tried to use the es5 files in the npm package but same result.
>
> I created a repository with a subset of our project, with the fallback (I commented out to test the IE longpolling error). If you start the backend and frontend you'll see IE keep sending connection requests.
>
> Other issue that if I enable my fallback method it still uses longpolling on Azure while it uses Websockets locally. Will deploy this example on Azure tomorrow.
>
> https://github.com/Marcelh1983/signalr-example
> signalR service: https://github.com/Marcelh1983/signalr-example/blob/master/Frontend/src/app/shared/services/signalr.service.ts

**Comment by moozzyk** [comment]
I will be changing the [no-cache header to nonce for long polling](https://github.com/aspnet/SignalR/issues/845 ) and will test this scenario.

**Comment by moozzyk** [comment]
@Marcelh1983 - I don't seem to be able to run this application. I think it fails on some kind of auth. 

![image](https://user-images.githubusercontent.com/1438884/30302689-8a8da5b4-9717-11e7-83a3-e598ef373bc8.png)

Can you create a trimmed version of the repro? 

I also sent a [PR](https://github.com/aspnet/SignalR/pull/851) to replace the `Cache-Control` header with nonce today and was able to run all the long polling tests on IE11, IE10 and IE9. 

One thing that you may want to check is that IE did not cache your script - maybe IE is using an old script without No-Cache even though you have a fixed version in your repo because it loads it from the cache. You may want to disable caching and/or reload your page with Ctrl+F5.

**Comment by moozzyk** [comment]
My bad - I did not notice that the backend server was running on port 25602.  Once I fixed I was able to run the sample in IE11 and Chrome and they communicated with each other just fine and IE did not cache xhr requests. I think you have a cached script somewhere.

![image](https://user-images.githubusercontent.com/1438884/30303084-6007b9da-971a-11e7-9d9e-0a94128d67fa.png)

**Comment by moozzyk** [comment]
Closing as no repro.

**Comment by Marcelh1983** [comment]
Thanks for having a look. I still get the error but maybe it is related to something else. I now use the es5 javascript files from the npm package. 

I deployed in here: http://signalr-core-example.azurewebsites.net
In Internet Explorer 11 it hangs, if I'm using long polling it keeps sending requests to the server immediately. On Azure it freezes for a while and after a while sending these authentication requests

![ie-calls](https://user-images.githubusercontent.com/3284645/30308542-61e1f740-9786-11e7-83dd-2dc579fe4bc6.png)

**Comment by Marcelh1983** [comment]
Other thing, but maybe that's another issue is that it uses long polling on azure:

![socketfail](https://user-images.githubusercontent.com/3284645/30308566-86ec7c7c-9786-11e7-968c-50b7fce149f3.png)

Locally it connects using websockets

**Comment by moozzyk** [comment]
Can you use non-minimized version? It is easier to debug because the line number will point to the location of the error. I wonder if the issue is that the url does not start with `ws://`/`wss://`. Can you set a breakpoint on this line and see what the url is and if it does not contain the protocol (`ws`) what url was passed to the transport?

**Comment by moozzyk** [comment]
Websockets don't work because you pass relative URL: 
![image](https://user-images.githubusercontent.com/1438884/30309227-1d35fc78-973f-11e7-8c74-b91e7c1cd4d4.png)

I just merged a change where relative urls are resolved so you need to update the client or pass full url.

**Comment by Marcelh1983** [comment]
Thanks! Can you also reproduce the ie11 long polling error? Click on a icon and wait like 1 minute. Any idea what the problem could be?

**Comment by moozzyk** [comment]
I can see it. No idea yet what's causing it because IE hangs due to the tight loop.

**Comment by moozzyk** [comment]
It seems that you are using some kind of polyfill of XmlHttpRequest. I am not sure why you do this but it does not seem to set/send the Cache-Control header and IE is serving xhr from the cache:
![image](https://user-images.githubusercontent.com/1438884/30309701-870e3ea6-9741-11e7-8db6-95636a229323.png)

I would recommend not using the polyfill - not sure why it is required. Also, I also merged a change this evening where we no longer rely on Cache-Control header to prevent IE from caching xhr requests. If you get this version this should fix the issue even if you use the polyfill.

**Comment by Marcelh1983** [comment]
Angular-cli provides all these polyfills which you should uncomment when you want internet explorer support. So maybe I should have looked in more detail to what I ucommented, but probably more people will do the same way as I do.

Thanks you  so much for looking into my issues!

**Comment by Marcelh1983** [comment]
I just tested with your merged code. Everything locally works fine, IE and chrome. On Azure it connects using websockets. So all the issues I experienced are solved.

Only problem now is that the client doesn't receive any signalR events while it works locally. I don't see any errors. I tried things like changing relative url to full, removing IE polyfills, deploying the dev build instead of minified one, but nothing helps.

**Comment by davidfowl** [comment]
@Marcelh1983 did you try turning logging on?

**Comment by Marcelh1983** [comment]
I set the logLevel on trace in the frontend. 

Get the message that it is connected. But no info/errors when the events should coming in.
Information: WebSocket connected to wss://signalr-core-example.azurewebsites.net/assignmentHub?authorization=eyJ0eXAiOiJKV1... 

Don't see any errors on the backend, and the backend isn't changed since the last version that worked,

**Comment by Marcelh1983** [comment]
Sorry probably something on my side. 

I send the events to the auth0-id which is stored in the User.Claims(). Somehow this is empty on azure. If I attach the debugger to Azure it works. Will try to find the problem.
